### ISSUE TITLE
Not working on Mint 21.3

### ISSUE THREAD

**Issue by mattipunkt** [miro011/linux-cinnamon-grouped-window-list-fork#1]
When you fresh-install your modification, mint will not display any grouped icons after restarting cinnamon

**Comment by miro011** [comment]
Alright. Will take a look hopefully this weekend.

**Comment by miro011** [comment]
.

**Comment by xencypher** [comment]
Thank you for all your effort on this feature.  I've tried to install the applet on a fresh install of Linux Mint 21.3 using the install script and unfortunately it does not seem to work.  Cinamon reports that applet.js could not load.  I've also checked that the permissions on the files were the same as the original grouped-window-list applet.

**Comment by miro011** [comment]
Yeah they updated it and I haven't had the time to fix it. Maybe over the weekend this week.

**Comment by miro011** [comment]
Never mind. I fixed the issue now. It was pretty simple.
